// Mocks generated by Mockito 5.4.6 from annotations
// in flutterhackthema/test/features/haiku/presentation/providers/haiku_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:flutterhackthema/features/haiku/data/models/haiku_model.dart'
    as _i3;
import 'package:flutterhackthema/features/haiku/data/repositories/haiku_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_1<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHaikuModel_2 extends _i1.SmartFake implements _i3.HaikuModel {
  _FakeHaikuModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HaikuRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHaikuRepository extends _i1.Mock implements _i4.HaikuRepository {
  MockHaikuRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get collectionPath =>
      (super.noSuchMethod(
            Invocation.getter(#collectionPath),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#collectionPath),
            ),
          )
          as String);

  @override
  _i2.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  _i2.CollectionReference<Map<String, dynamic>> get collection =>
      (super.noSuchMethod(
            Invocation.getter(#collection),
            returnValue: _FakeCollectionReference_1<Map<String, dynamic>>(
              this,
              Invocation.getter(#collection),
            ),
          )
          as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i6.Future<String> create(_i3.HaikuModel? data, {String? docId}) =>
      (super.noSuchMethod(
            Invocation.method(#create, [data], {#docId: docId}),
            returnValue: _i6.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#create, [data], {#docId: docId}),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i3.HaikuModel fromFirestore(
    _i2.DocumentSnapshot<Map<String, dynamic>>? snapshot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fromFirestore, [snapshot]),
            returnValue: _FakeHaikuModel_2(
              this,
              Invocation.method(#fromFirestore, [snapshot]),
            ),
          )
          as _i3.HaikuModel);

  @override
  Map<String, dynamic> toFirestore(_i3.HaikuModel? data) =>
      (super.noSuchMethod(
            Invocation.method(#toFirestore, [data]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<_i3.HaikuModel?> read(String? docId) =>
      (super.noSuchMethod(
            Invocation.method(#read, [docId]),
            returnValue: _i6.Future<_i3.HaikuModel?>.value(),
          )
          as _i6.Future<_i3.HaikuModel?>);

  @override
  _i6.Future<void> update(String? docId, _i3.HaikuModel? data) =>
      (super.noSuchMethod(
            Invocation.method(#update, [docId, data]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> delete(String? docId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [docId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.HaikuModel>> readAll() =>
      (super.noSuchMethod(
            Invocation.method(#readAll, []),
            returnValue: _i6.Future<List<_i3.HaikuModel>>.value(
              <_i3.HaikuModel>[],
            ),
          )
          as _i6.Future<List<_i3.HaikuModel>>);

  @override
  _i6.Stream<List<_i3.HaikuModel>> watchAll({
    _i2.Query<Map<String, dynamic>>? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, [], {#query: query}),
            returnValue: _i6.Stream<List<_i3.HaikuModel>>.empty(),
          )
          as _i6.Stream<List<_i3.HaikuModel>>);

  @override
  _i6.Stream<_i3.HaikuModel?> watch(String? docId) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [docId]),
            returnValue: _i6.Stream<_i3.HaikuModel?>.empty(),
          )
          as _i6.Stream<_i3.HaikuModel?>);
}
