// Mocks generated by Mockito 5.4.6 from annotations
// in flutterhackthema/test/features/haiku/presentation/providers/image_save_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i6;

import 'package:firebase_storage/firebase_storage.dart' as _i2;
import 'package:flutterhackthema/features/haiku/data/repositories/haiku_image_storage_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseStorage_0 extends _i1.SmartFake
    implements _i2.FirebaseStorage {
  _FakeFirebaseStorage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReference_1 extends _i1.SmartFake implements _i2.Reference {
  _FakeReference_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HaikuImageStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHaikuImageStorageRepository extends _i1.Mock
    implements _i3.HaikuImageStorageRepository {
  MockHaikuImageStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get basePath =>
      (super.noSuchMethod(
            Invocation.getter(#basePath),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#basePath),
            ),
          )
          as String);

  @override
  _i2.FirebaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFirebaseStorage_0(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i2.FirebaseStorage);

  @override
  _i2.Reference get baseRef =>
      (super.noSuchMethod(
            Invocation.getter(#baseRef),
            returnValue: _FakeReference_1(this, Invocation.getter(#baseRef)),
          )
          as _i2.Reference);

  @override
  _i5.Future<String> uploadHaikuImage({
    required _i6.Uint8List? imageData,
    String? haikuId,
    String? userId,
    _i3.HaikuImageMetadata? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadHaikuImage, [], {
              #imageData: imageData,
              #haikuId: haikuId,
              #userId: userId,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#uploadHaikuImage, [], {
                  #imageData: imageData,
                  #haikuId: haikuId,
                  #userId: userId,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> upload(
    String? fileName,
    _i6.Uint8List? data, {
    _i2.SettableMetadata? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upload, [fileName, data], {#metadata: metadata}),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #upload,
                  [fileName, data],
                  {#metadata: metadata},
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i6.Uint8List?> download(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#download, [fileName]),
            returnValue: _i5.Future<_i6.Uint8List?>.value(),
          )
          as _i5.Future<_i6.Uint8List?>);

  @override
  _i5.Future<void> delete(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [fileName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getDownloadUrl(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [fileName]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<List<_i2.Reference>> listFiles({String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#listFiles, [], {#path: path}),
            returnValue: _i5.Future<List<_i2.Reference>>.value(
              <_i2.Reference>[],
            ),
          )
          as _i5.Future<List<_i2.Reference>>);

  @override
  _i5.Future<_i2.FullMetadata?> getMetadata(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, [fileName]),
            returnValue: _i5.Future<_i2.FullMetadata?>.value(),
          )
          as _i5.Future<_i2.FullMetadata?>);
}
